services:
  electrons-ruby:
    container_name: electrons-app
    image: registry.gitlab.com/schusco/electrons_ruby:latest
    user: "1000:1000"
    restart: always  # This handles the "Auto-Run" on crash or reboot
    volumes:
      - /home/ec2-user/electrons_ruby/public:/app/public # Persistent volume mapping
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DB_HOST=${DB_HOST}
      - ELECTRONS_DATABASE_PASSWORD=${DB_PASSWORD}
    networks:
      - electrons-bridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"] # Rails 7+ has a built-in /up health check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
networks:
  electrons-bridge:
    name: scoreboardapi_electron-net
    external: true
